name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag batu:latest

    - name: Anchore SBOM Action
      uses: anchore/sbom-action@v0.15.11
      with:
        image: batu:latest
        artifact-name: batu-latest-sbom

    - name: Upload SBOM Artifact
      uses: actions/upload-artifact@v4
      with:
        name: batu-latest-sbom
        path: ./sbom/**/*
